[package]
name = "floneum-docs"
version = "0.0.1"
edition = "2021"
description = "Floneum docs with tested examples"
license = "MIT/Apache-2.0"
publish = false

[dependencies]
floneum_rust = { path = "../rust_adapter" }
