[package]
name = "floneum-site"
version = "0.1.0"
edition = "2021"
authors = ["Evan Almloff"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history", features = ["fullstack", "router"] }
syntect-html = { git = "https://github.com/dioxuslabs/include_mdbook", branch = "update-to-dioxus-next" }
mdbook-shared = { git = "https://github.com/dioxuslabs/include_mdbook", branch = "update-to-dioxus-next" }
use-mdbook = { git = "https://github.com/dioxuslabs/include_mdbook", branch = "update-to-dioxus-next" }
dioxus-search = { git = "https://github.com/dioxuslabs/dioxus-search", branch = "dioxus-next" }

manganis = { git = "https://github.com/DioxusLabs/collect-assets" }

tokio = { version = "1.29.0", features = ["full"], optional = true }
axum = { version = "0.6.12", optional = true }
simple_logger = "4.2.0"
log = "0.4.17"
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"
serde = { version = "1.0.164", features = ["derive"] }
getrandom = { version = "0.2", features = ["js"] }
postcard = { version = "1.0.4", features = ["use-std"] }
futures-util-preview = "0.2.2"
anyhow = { version = "1.0.75", optional = true }

kalosm = { git = "https://github.com/floneum/floneum", optional = true }
image = { version = "0.24.7", optional = true }
slab = "0.4.9"
wasm-bindgen = "0.2.91"
web-sys = { version = "0.3.64", features = [
    "Document",
    "Window",
    "Event",
    "AddEventListenerOptions",
] }
gloo-timers = { version = "0.2.6", features = ["futures"] }
js-sys = "0.3.64"
fs_extra = { version = "1.3.0", optional = true }

[dev-dependencies]
floneum_rust = { git = "https://github.com/floneum/floneum" }
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen" }

[build-dependencies]
tokio = { version = "1", features = ["full"] }
floneumite = { git = "https://github.com/floneum/floneum" }
postcard = { version = "1.0.4", features = ["use-std"] }
serde = { version = "1.0.164", features = ["derive"] }

[patch.'https://github.com/dioxuslabs/dioxus']
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-lib = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-core = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-core-macro = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-signals = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-html = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-cli-config = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-router = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-router-macro = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-rsx = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }

dioxus-web = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-ssr = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-tui = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-desktop = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-liveview = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-fullstack = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-native-core = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-native-core-macro = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }

[patch.crates-io]
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-lib = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-core = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-core-macro = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-signals = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-html = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-cli-config = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-router = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-router-macro = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-rsx = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }

dioxus-web = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-ssr = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-tui = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-desktop = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-liveview = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-fullstack = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-native-core = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }
dioxus-native-core-macro = { git = "https://github.com/ealmloff/dioxus", branch = "fix-fullstack-history" }

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'
strip = "debuginfo"

[features]
default = []
web = ["dioxus/web"]
ssr = ["tokio", "dioxus/axum", "axum"]
prebuild = ["ssr", "fs_extra"]
check_docs = ["kalosm", "tokio", "anyhow", "image"]
