[profile]

[profile.dioxus-client]
inherits = "dev"
opt-level = 2

[profile.dioxus-server]
inherits = "dev"
opt-level = 2
# [unstable]
# build-std = ["std", "panic_abort", "core", "alloc"]
# build-std-features = ["panic_immediate_abort"]